target hello
sources examples/hello/main.cpp examples/hello/Greeter.cpp
headers examples/hello/Greeter.hpp
objects .dagbuild/objects/hello
output .dagbuild/hello
end

target goodbye
sources examples/goodbye/main.cpp
objects .dagbuild/objects/goodbye
output .dagbuild/goodbye
end
